### ISSUE TITLE
8800 Phone Extended Line Mode - right hand programmable buttons not accessible

### ISSUE THREAD

**Issue by jamesha100** [avholloway/cisco-phone-controller#2]
Great software - when an 8841 is configured for Extended Line Mode the five programmable buttons on the right hand side of the phone do not respond when clicked.

**Comment by avholloway** [comment]
Ah yes, that would be the case, since the action for those buttons is set to Session buttons and not Line buttons.  I'll see if there is some way for me to detect which line mode the phone is in, and switch it automatically, or perhaps have a user toggle for this.  In the mean time, if you need to press those buttons, use the Macro box and use Line6, Line7, Line8, Line9, Line10

**Comment by avholloway** [comment]
No intention of adding enhanced line mode for now.  Will consider in a future update.
